# Generated by Django 4.2.3 on 2023-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travllo2', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default='defult'),
            preserve_default=False,
        ),
    ]
